### ISSUE TITLE
vault_node_name unused

### ISSUE THREAD

**Issue by Gurpartap** [ansible-community/ansible-vault#101]
Setting `vault_node_name` has no effect because it is not implemented in the template for `vault_main.hcl`.

https://github.com/brianshumate/ansible-vault/search?q=vault_node_name&unscoped_q=vault_node_name

**Comment by Gurpartap** [comment]
Apparently, there's no node name option in [vault config](https://www.vaultproject.io/docs/configuration/) or [vault's consul storage config](https://www.vaultproject.io/docs/configuration/storage/consul.html)

I had thought setting the node_name would affect the consul service ID of each vault instance.

However, vault's consul service id is hardcoded to be `service_name:host:port`. Node name doesn't come into play.

It might be good to remove any reference to `vault_node_name` from the readme file.

**Comment by brianshumate** [comment]
Hi, thanks for the heads up.

`vault_node_name` is indeed nonfunctional; it has been removed in Master and will no longer be present in the v2.2.2 role version when it is released.
