### ISSUE TITLE
Support tls files in subdirectories

### ISSUE THREAD

**Issue by sroughto** [ansible-community/ansible-vault#110]
Our Vault VMs came with pre-installed TLS keys, certs, and CAs. These were located in subdirectories of `/etc/pki/tls` (e.g., `/etc/pki/tls/private`).

We tried to work around this by defining TLS location variables to include a subdirectory, such as:

    vault_tls_key_file: private/server-vault.key

However, this breaks the Ansible role (because, in this example, `private` does not exist under the destination `vault_tls_config_path`, resulting in a file not found error).

To proceed, we could either (a) copy the files to a single source directory so the role would work as-is, (b) modify the role to create subdirectories under `vault_tls_config_path`, or (c) modify the role to copy files from source subdirectories into `vault_tls_config_path` without subdirectories. We chose the latter.

The simplest approach was to add a "basename" filter where TLS variables were used, e.g.,

    - dest: "{{ vault_tls_config_path }}/{{ vault_tls_key_file }}"
    + dest: "{{ vault_tls_config_path }}/{{ vault_tls_key_file | basename }}"

This enables `vault_tls_key_file` (and other TLS source location variables) to include a subdirectory prefix. This change should be backward-compatible with existing playbooks that expect TLS source files co-located in one directory.

This change is needed in several files (`tasks/main.yml`, `tasks/tls.yml`, `templates/vault_backend_consul.j2`, `templates/vault_backend_etcd.j2`, and `templates/vault_main_configuration.hcl.j2`), for the following variables:

* `vault_tls_cert_file`
* `vault_tls_key_file`
* `vault_tls_ca_file`

**Comment by sroughto** [comment]
fyi this is a corollary to a similar issue for the Consul playbook (https://github.com/brianshumate/ansible-consul/issues/297).

Please let us know if we should go ahead and simply copy the source files to a single subdirectory going forward, or try some other approach.

**Comment by bbaassssiiee** [comment]
### Corporate PKI
To add a certificate in the simple PEM or DER file formats to the list of CAs trusted on the system:

Copy it to the subdirectory:
```
    /etc/pki/ca-trust/source/anchors/
```
and run the command:
```
 update-ca-trust
```

If your certificate is in the extended BEGIN TRUSTED file format,
then place it into the main source/ directory instead.

**Comment by bbaassssiiee** [comment]
copy the files to a single source directory so the role would work as-is
