### ISSUE TITLE
api_addr should match TLS certificate

### ISSUE THREAD

**Issue by bbaassssiiee** [ansible-community/ansible-vault#122]
` /etc/vault.d/vault_main.hcl` has an IP address for api_addr, this is not included in my certificate.
This causes a TLS problem when I try using [Seth Vargo's Plugin](https://github.com/sethvargo/vault-secrets-gen) 

```
api_addr = "https://10.1.1.64:8200"
```

I would rather use "{{ ansible_fqdn }}" or "{{ inventory_hostname }}". Why not?

**Comment by ericsysmin** [comment]
I am working on a 2nd pr that should fix this as it causes issues for me as well

**Comment by ericsysmin** [comment]
@bbaassssiiee does that PR help?

**Comment by bbaassssiiee** [comment]
Yes it does, thanks!
