### ISSUE TITLE
"msg": "hostname '10.138.0.95' doesn't match 'vault.ericsysmin.local'",

### ISSUE THREAD

**Issue by ericsysmin** [ansible-community/ansible-vault#124]
https://github.com/brianshumate/ansible-vault/blob/d3f4353c5ed9a1da120cc484b8c3ad106de9099f/tasks/main.yml#L238

This line here doesn't allow you to use a valid domain name so it will fail due to validate certs on https.

**Comment by bbaassssiiee** [comment]
https://github.com/ansible-community/ansible-vault/pull/128 was merged
