### ISSUE TITLE
linting issue with   when: "'{{ check_result.status }}' in item.key"

### ISSUE THREAD

**Issue by ericsysmin** [ansible-community/ansible-vault#127]
We get a lint warning from ansible-lint on this, we should look at an alternative

**Comment by ericsysmin** [comment]
https://github.com/brianshumate/ansible-vault/pull/129 has been submitted to fix

**Comment by bbaassssiiee** [comment]
https://github.com/ansible-community/ansible-vault/pull/129 was merged.
