### ISSUE TITLE
Consider using local_action: over connection: local

### ISSUE THREAD

**Issue by hansnqyr** [ansible-community/ansible-vault#13]
connection: local does not change the target host - it simply changes the connection plugin to local.
See: https://github.com/ansible/ansible/issues/16724#issuecomment-269994368

This becomes problematic because the localhost inventory is not used for the task - the remote node inventory is used instead. 

local_action is designed for running tasks on the ansible host and correctly uses the localhost inventory.

**Comment by hansnqyr** [comment]
Hi, first up really appreciate the quick response on this even if it didn't work out straight away, thanks.
Second, I'm happy to work on a PR to help with this.

My localhost and remote servers don't have common environment settings, they differ in at least python and proxy server details. For this reason, connection: local doesn't work for me.

Further details:
```
hosts.ini
some_server ansible_python_interpreter=/usr/bin/python
localhost   ansible_python_interpreter=/usr/local/bin/python
```
**Test**: Run a task using connection: local
**Expectation**: task uses /usr/local/bin/python
**Result**: task tries to use /usr/bin/python

Same thing holds true for environment settings such as proxy etc.

Can you give some detail on how local_action broke?

**Comment by brianshumate** [comment]
Hi,

Thanks for the update; I'll go ahead and reopen this.

I think this is related to another issue I have seen with the `connection: local` tasks as well.

I'll update here with the error I see when converting them to `local_action`.

**Comment by dagwieers** [comment]
This relates to https://github.com/ansible/ansible/issues/24076
