### ISSUE TITLE
Default tls names differs from documentation

### ISSUE THREAD

**Issue by zarath** [ansible-community/ansible-vault#136]
Hi,
great ansible role!
I figured out a small glitches in documentation / defaults/main.yml of roles vars.

- vault_tls_cert_file defaults to vault.crt
- vault_tls_key_file defaults to vault.key

in READMD.md these variables defaults are document as
- server.crt
- server.key

I personally would like the later as it would be consistent with your ansible-consul role.

regards
    Holger

**Comment by bbaassssiiee** [comment]
Would you be so kind as to create a pull-request? You will be listed in [CONTRIBUTORS.md](https://github.com/ansible-community/ansible-vault/blob/master/CONTRIBUTORS.md) ?
