### ISSUE TITLE
Support self-signed tls by dropping the requirement for vault_tls_ca_file

### ISSUE THREAD

**Issue by Throckmortra** [ansible-community/ansible-vault#141]
Hello, 

If self-signing a cert with a tool like openssl, no CA file is created. Your role currently requires one. Would you consider adding a flag for disabling this?

**Comment by bbaassssiiee** [comment]
`consul tls ca create`

**Comment by bbaassssiiee** [comment]
This is an ansible-role to secure IT environments, it relies on TLS. It is trivial to create a CA yourself, and use its key to sign your servers. Adding a flag to disable trust is bad. Won't do it.
