### ISSUE TITLE
Provide an "agent only" mode

### ISSUE THREAD

**Issue by proffalken** [ansible-community/ansible-vault#143]
Some of the nodes in our infrastructure require the vault agent to be installed without configuring it as a server so that they can authenticate via various means or query the cluster state.

It would be great if there were a configuration flag on the role that installed Vault in "agent mode only".

I'm happy to contribute this code if we can agree on a design, but I'm hoping that this exists already and that I've missed the appropriate flag! :)

**Comment by ahmadalli** [comment]
I've tried to find options for agent mode but I couldn't find any. That would be great if we could have agent only mode

**Comment by bbaassssiiee** [comment]
You can install the `vault` binary for that purpose, right?

**Comment by ahmadalli** [comment]
if you want to automate downloading, configuration and have a proper systemd service in order to keep agent up and running (e.g. on a ci/cd runner vm) you'll end up doing almost all the things this role will do :)

**Comment by ahmadalli** [comment]
the same vault binary as the server's is used for the vault agent

**Comment by proffalken** [comment]
Yeah, apologies, bad wording on my part.

I guess I'm looking for an "install the binary, but don't configure it as a vault server" flag :)

**Comment by bbaassssiiee** [comment]
DId https://github.com/ansible-community/ansible-vault/pull/204 fix your use-case?

**Comment by proffalken** [comment]
@bbaassssiiee - possibly, however I'm not responsible for that infrastructure anymore so I'm unable to test it, sorry :(

**Comment by ahmadalli** [comment]
I needed more complex setup (setting up templating and other things) and I ended up developing my own ansible role. https://github.com/ahmadalli/ansible/tree/main/roles/hashicorp/vault/agent

**Comment by bbaassssiiee** [comment]
Thanks! Good for the record.
