### ISSUE TITLE
fatal: [server01.consul -> 127.0.0.1]: FAILED! => {"changed": false, "cmd": "/bin/bash -c 'set -o pipefail\ngrep \"vault_1.3.2_linux_amd64.zip\" 

### ISSUE THREAD

**Issue by tickers** [ansible-community/ansible-vault#151]
fatal: [server01.consul -> 127.0.0.1]: FAILED! => {"changed": false, "cmd": "/bin/bash -c 'set -o pipefail\ngrep \"vault_1.3.2_linux_amd64.zip\" \"/etc/ansible/roles/brianshumate.vault/files/vault_1.3.2_SHA256SUMS\" | awk '\"'\"'{print $1}'\"'\"'\n'", "msg": "[Errno 2] No such file or directory: b'/bin/bash'", "rc": 2}
v2.5.2

Check the SHA file against the HashiCorp one and it matches there so not sure where else to look.

**Comment by bbaassssiiee** [comment]
You don't have `/bin/bash`, what platform are you using?

**Comment by bbaassssiiee** [comment]
Could this be caused by trying to install this role without a writable path?

**Comment by bbaassssiiee** [comment]
Install the role with:
`ansible-galaxy install -p yourdir`

yourdir should be writable by the ansible user, so likely a project subdir instead of in /etc/ansible
