### ISSUE TITLE
Missing attributes in seal template

### ISSUE THREAD

**Issue by kvonbredow** [ansible-community/ansible-vault#158]
When attempting to use the Azure KMS seal, the generated configuration only contained the `tenant_id` and if I'm understanding correctly it looks like the `bool` filter is preventing these values from landing in the template -
```
seal "azurekeyvault" {
  tenant_id     = "{{ vault_azurekeyvault_tenant_id }}"
{% if vault_azurekeyvault_client_id | bool %}
  client_id     = "{{ vault_azurekeyvault_client_id }}"
{% endif %}
...
}
``` 

The ansible docs state that this filter is used for truthy strings so I'm pretty sure this is the problem, but it looks like these were added deliberately so I wanted to make sure before filing a PR. ([Update template filenames, apply bool filter, and update docs](https://github.com/ansible-community/ansible-vault/commit/a833b3bd2920ac6a35bf2b2ab3782fe7a150ee6d))

https://docs.ansible.com/ansible/latest/user_guide/playbooks_conditionals.html -
> Variables defined in the playbooks or inventory can also be used, just make sure to apply the |bool filter to non boolean variables (ex: string variables with content like ‘yes’, ‘on’, ‘1’, ‘true’).

**Comment by jdelaporte** [comment]
If I understand the problem, the template's conditional should be updated to the following:

...
{% if vault_azurekeyvault_client_id is defined %}
  client_id     = "{{ vault_azurekeyvault_client_id }}"
{% endif %}
...

**Comment by bbaassssiiee** [comment]
Correct, would you be so kind as of to create a pull-request for this?
