### ISSUE TITLE
New name for this role?

### ISSUE THREAD

**Issue by zmingxie** [ansible-community/ansible-vault#175]
While I was testing my change for https://github.com/ansible-community/ansible-vault/pull/174, I also noticed Ansible Galaxy still only has Brian's old role: https://galaxy.ansible.com/brianshumate/vault

Should we create a new one for the community repo now?

**Comment by bbaassssiiee** [comment]
I'm trying to connect to Chris Houseknecht to help resolve the problem of publishing to Galaxy.

**Comment by zmingxie** [comment]
Thanks @bbaassssiiee. I also wonder if we want to rename this role to 'hashi-vault' instead of 'ansible-vault'.

This is because `ansible-vault` could also mean the command that people use for encrypting content in ansible: https://docs.ansible.com/ansible/latest/user_guide/vault.html

**Comment by bbaassssiiee** [comment]
I updated the meta-data instead, should be clear now.
