### ISSUE TITLE
Feature Request: decrypt_string

### ISSUE THREAD

**Issue by TheSecMaven** [ansible-community/ansible-vault#181]
Vault provides encrypt_string function, it is a huge issue to ask our users to deal with the debug module and the difficulties of that when needing to decrypt, but not encrypt. To provide a consistent user and customer experience, we should offer decrypt_string function that works just like encrypt_string but in reverse.

**Comment by bbaassssiiee** [comment]
This repo deals with the deployment of Hashicorp Vault using Ansible. You might want to post your issue in the appropriate product repo.
