### ISSUE TITLE
--vault-id does not work as expected

### ISSUE THREAD

**Issue by scott2b** [ansible-community/ansible-vault#183]
ansible-vault version:
2.10.3

Expected behavior:
--vault-id with a specified ID and source (ie, the file name of a password file) would use the identified password for encryption and decryption operations

Actual behavior:
Unclear, but it appears that the contents of the entire file is being used, not the labeled password. Any modifications to the password file, such as adding a new labeled password, or changing the order of labeled passwords, results in the inability to decrypt the file. Likewise, decryption is not possible by passing in the password on the command line, further indication that the labeled password was not actually used for encryption.

To replicate:

```
$ echo "test" > test.txt
$ cat test.txt
test

$ echo "foo thepassword" > pwfile.txt
$ cat pwfile.txt
foo thepassword

$ ansible-vault encrypt --vault-id foo@./pwfile.txt test.txt
Encryption successful

$ ansible-vault view --vault-id foo@./pwfile.txt test.txt
test

$ echo "bar anotherpassword" >> pwfile.txt

$ cat pwfile.txt
foo thepassword
bar anotherpassword

$ ansible-vault view --vault-id foo@./pwfile.txt test.txt
ERROR! Decryption failed (no vault secrets were found that could decrypt) on test.txt for test.txt
```

**Comment by bbaassssiiee** [comment]
This repo is a role to deploy Hashicorp Vault using ansible.
