### ISSUE TITLE
Vault cannot be stopped/restarted with systemd

### ISSUE THREAD

**Issue by DaazKu** [ansible-community/ansible-vault#192]
Pre-conditions:
- os: Ubuntu 20.4
- logging turned on

I cannot properly stop or restart Vault with systemd because [it is executed in a subshell](https://github.com/ansible-community/ansible-vault/commit/a7b76466e1c2949c28f2db0d935d8a2e8a82d419#diff-2c0cdc895780005b16477aa338c276a01ba313763393e446b0d5609f92a1e017R33).
The command hangs util timeout is reached and the actual process is not stopped.

If I revert that back everything now works properly.

**Edit: Proper solution without using `StandardOutput/StandardError` #196**

----------------

In my case I was able to revert back and add the following under `[service]` instead.
```
StandardOutput=file:{{ vault_log_path }}/vault-output.log
StandardError=file:{{ vault_log_path }}/vault-error.log
```

The above is a feature of systemd v236 and [ubuntu 18.4 come with systemd v237](https://launchpad.net/ubuntu/bionic/+source/systemd) so that should be good on that front but Debian is a problem....
I don't know how to "fix" otherwise.

Here's the full template I ended up using:
```
### BEGIN INIT INFO
# Provides:          vault
# Required-Start:    $local_fs $remote_fs
# Required-Stop:     $local_fs $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Vault agent
# Description:       Vault secret management tool
### END INIT INFO

[Unit]
Description="HashiCorp Vault - A tool for managing secrets"
Documentation=https://www.vaultproject.io/docs/
Requires=network-online.target
After=network-online.target
ConditionFileNotEmpty={{ vault_main_config }}
StartLimitInterval=60

[Service]
User={{ vault_user }}
Group={{ vault_group }}
ProtectSystem=full
ProtectHome=read-only
PrivateTmp=yes
PrivateDevices=yes
SecureBits=keep-caps
Capabilities=CAP_IPC_LOCK+ep
{% if systemd_version.stdout is version('230', '>=') %}
AmbientCapabilities=CAP_SYSLOG CAP_IPC_LOCK
{% endif %}
CapabilityBoundingSet=CAP_SYSLOG CAP_IPC_LOCK
NoNewPrivileges=yes
ExecStart={{ vault_bin_path }}/vault server -config={{ vault_main_config }} -log-level={{ vault_log_level | lower }}
ExecReload=/bin/kill --signal HUP $MAINPID
KillMode=process
KillSignal=SIGINT
Restart=on-failure
RestartSec=5
TimeoutStopSec=30
StartLimitIntervalSec=60
StartLimitBurst=3
LimitNOFILE=524288
LimitNPROC=524288
LimitMEMLOCK=infinity
StandardOutput=file:{{ vault_log_path }}/vault-ouput.log
StandardError=file:{{ vault_log_path }}/vault-error.log

[Install]
WantedBy=multi-user.target
```

P.S. logrotate would need to also be updated with the above since vault.err would also need to be rotated.

**Comment by bbaassssiiee** [comment]
Please test and comment on this [PR]( https://github.com/ansible-community/ansible-vault/pull/186)

**Comment by DaazKu** [comment]
@bbaassssiiee the PR you mentionned does not work. Made one that works.

**Comment by willhaines** [comment]
I'm not a maintainer or anything, but I think the PR from @DaazKu is the best way to fix this.
