### ISSUE TITLE
Please resume making tagged releases

### ISSUE THREAD

**Issue by willhaines** [ansible-community/ansible-vault#195]
It appears that the last tagged release occurred when this project was taken over by the community, and the recommendation is now to use the master branch directly.

This is not ideal in a production environment, since some regressions (such as #192) are inevitable. If versioned releases were made regularly, even on an arbitrary schedule such as the 1st of every month, it would be much easier for users to revert to a previous version while bugs are fixed.

**Comment by bbaassssiiee** [comment]
Fair point, but we now maintain this in our free time, if any. I pushed  v2.5.5 

BTW: You can use any tag in `roles/requirements.yml`.

**Comment by willhaines** [comment]
How would you feel about something like automated monthly snapshots -- generated with github actions:

    name: Release Monthly Snapshot

    on:
      schedule:
      - cron: "0 0 * 1 *"

    jobs:
      build:
        name: Release Monthly Snapshot
        runs-on: ubuntu-latest
        steps:
          - name: Get current date
            id: date
            run: echo "DATE=$(date +'%Y.%m.%d')" >> $GITHUB_ENV
          - name: Checkout master Branch
            uses: actions/checkout@v2
            with:
              ref: 'master'
          - name: Create Release
            id: monthly-snapshot
            uses: actions/create-release@latest
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            with:
              tag_name: ${{ env.DATE }}
              release_name: "Monthly snapshot for ${{ env.DATE }}"
              draft: false
              prerelease: false


I realize that this is a departure from semantic versioning, but I have confirmed that `ansible-galaxy install -r requirements.yml` accepts this tag format. If you're open to the idea, I will do some formal testing in a separate repo and make a PR.

Also, regarding maintenance, if our team continues to use this role, we could contribute some work time for maintenance if that would help.

**Comment by bbaassssiiee** [comment]
That offer is very kind of you!
