### ISSUE TITLE
Support multiple listeners

### ISSUE THREAD

**Issue by ghost** [ansible-community/ansible-vault#208]
This is a feature request for supporting multiple listeners.

Use case example: Add a second listener that checks client certificates.

Suggested approach:
* Extract listener config from the `vault_main_configuration.hcl` and put it into separate templates which are sourced depending on the number of listeners required
* Group the listener variables in a list, make an item for each listener

**Comment by bbaassssiiee** [comment]
Fixed by https://github.com/ansible-community/ansible-vault/pull/210
