### ISSUE TITLE
AnsibleUndefinedVariable: 'ansible.vars.hostvars.HostVarsVars object' has no attribute ansible_eth0

### ISSUE THREAD

**Issue by fajarnugroho** [ansible-community/ansible-vault#211]
This error happened when using raft as storage backend.
```
TASK [ansible-community.ansible-vault : Vault main configuration] **********************
fatal: [server-1.company.internal]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'ansible.vars.hostvars.HostVarsVars object' has no attribute 'ansible_eth0'"}
```

local machine details:
```
ansible-playbook 2.10.4
  config file = None
  configured module search path = ['/Users/nugrohof/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.10.5/libexec/lib/python3.9/site-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 3.9.1 (default, Jan  8 2021, 17:17:43) [Clang 12.0.0 (clang-1200.0.32.28)]

Mac OS Big Sur 11.1
```

remote machine details:
```
Ubuntu 18.04.4 LTS
```

**Comment by bbaassssiiee** [comment]
It's due to a concatenation, look at the ethernet interface name on your machine and define something like:
```
vault_iface: eth1
```

**Comment by rkacg** [comment]
Hi,
i get the same error as fajarnugroho no matter if i omit or set the vault_iface parameter

**Error Message**
`TASK [ansible-vault : Vault main configuration] *****************************************************************************
fatal: [vault1.sec.austrocontrol.at]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'ansible.vars.hostvars.HostVarsVars object' has no attribute 'ansible_ens160'"}`

**Server Interfaces:**
`[root@vault1 vault.d]# ip link
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: ens160: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP mode DEFAULT group default qlen 1000
    link/ether 00:50:56:ae:77:81 brd ff:ff:ff:ff:ff:ff`

**Playbok:**

hosts: vault
   gather_facts: True
   become: yes

   pre_tasks:
     - include: "tasks/vault.yaml"

   vars_files:
     - "vars/vault-certificate.yaml"

   vars:
    vault_version: 1.6.2
    vault_data_path: /var/vault
    vault_raft_data_path: /var/vault
    vault_raft_group_name: vault
    vault_group: vault
    vault_manage_group: true
    vault_cluster_name: vault
    **vault_iface: ens160**
    vault_backend: raft
    vault_raft_node_id: "{{ ansible_facts.nodename }}"
    vault_api_addr: "{{ vault_protocol }}://{{ ansible_facts.nodename }}:{{ vault_port }}"
    vault_address: "{{ ansible_facts.nodename }}"
    vault_cluster_addr: "{{ vault_protocol }}://{{ ansible_facts.nodename }}"
    vault_port: 8200
    vault_tls_disable: 0
    vault_tls_copy_keys: true
    vault_tls_files_remote_src: true
    vault_tls_src_files: /etc/ssl
    vault_tls_ca_file: ca.crt
    vault_tls_cert_file: server.crt
    vault_tls_key_file: server.key

  roles:
    - { role: ansible-vault }

**Comment by rkacg** [comment]
Hi,

I think I've found the error:

This is out of your docu
Default value: "{{ hostvars[**inventory_hostname**]['ansible_'+vault_iface]['ipv4']['address'] }}"

but in the file /.ansible/roles/ansible-vault/templates/vault_backend_raft.j2 you use this:

"{{ hostvars[**server**]['vault_api_addr'] | default(vault_protocol + '://' + hostvars[**server**]['ansible_' + vault_iface]['ipv4']['address'] + ':' + (vault_port|string)) }}"

If you replace server with inventory_hostname  everything works fine.

BR
Rene

**Comment by fajarnugroho** [comment]
> It's due to a concatenation, look at the ethernet interface name on your machine and define something like:
> 
> ```
> vault_iface: eth1
> ```

Hi @bbaassssiiee, thanks for your response. I have set the `vault_iface` value and the interface is exist.

**Comment by fajarnugroho** [comment]
Hi @rkacg,

Thanks for your help.
I've found out that `hostvars[server]` doesn't contain `ansible_eth0` key. So, I change the key to `ansible_host`.

This is the line that I changed in `templates/vault_backend_raft.j2` file:
```
leader_api_addr = "{{ hostvars[server]['vault_api_addr'] | default(vault_protocol + '://' + hostvars[server]['ansible_host'] + ':' + (vault_port|string))  }}"
```

I think the purpose of the variable is to customize which IP address/interface that will be used for exposing Vault port. So, I will close this issue.

**Comment by bbaassssiiee** [comment]
I guess @rkacg might be right about a bug in the template.

Please try with `inventory_hostname` instead of `ansible_host`. 

The output of this command should have the interface name in your situation:
```
ansible vault_servers -m setup 
```

**Comment by fajarnugroho** [comment]
Hi @bbaassssiiee 

I tried to debug by inserting a task before the `Vault main configuration` task to see the content of `hostvars`. In that case, the `ansible_eth0` key was presented. But, when I tried to debug by modifying the `Vault main configuration` task by dumping `hostvars` variable to `/etc/vault.d/vault_main.hcl` there is no `ansible_eth0` key presented.

**Comment by bbaassssiiee** [comment]
> Hi,
> 
> I think I've found the error:
> 
> This is out of your docu
> Default value: "{{ hostvars[**inventory_hostname**]['ansible_'+vault_iface]['ipv4']['address'] }}"
> 
> but in the file /.ansible/roles/ansible-vault/templates/vault_backend_raft.j2 you use this:
> 
> "{{ hostvars[**server**]['vault_api_addr'] | default(vault_protocol + '://' + hostvars[**server**]['ansible_' + vault_iface]['ipv4']['address'] + ':' + (vault_port|string)) }}"
> 
> If you replace server with inventory_hostname everything works fine.
> 
> BR
> Rene

Can you provide a pull-request?

**Comment by adrianmoisey** [comment]
I've had the same issue, and made a PR here: https://github.com/ansible-community/ansible-vault/pull/230

**Comment by patsevanton** [comment]
@rkacg Could you show contain tasks/vault.yaml and vars/vault-certificate.yaml ? Thanks!

**Comment by ramil1973** [comment]
So Im guessing that if you have a machine listed in your inventory that you are not using anymore it can cause issues with magic variables.

**Comment by boldandbusted** [comment]
I'm getting bit by this. It only seems to show up when I try to limit the hosts targeted. Example: in a `--limit 'group:!hostname'` scenario. It's really not great for operational tasks, like upgrading Vault using HashiCorp's Upgrade proceedures: https://learn.hashicorp.com/tutorials/vault/sop-upgrade?in=vault/standard-procedures

```
Vault main configuration...
  <hostname redacted> failed | msg: AnsibleUndefinedVariable: 'ansible.vars.hostvars.HostVarsVars object' has no attribute u'ansible_eth0'
```

**Comment by boldandbusted** [comment]
> So Im guessing that if you have a machine listed in your inventory that you are not using anymore it can cause issues with magic variables.

But what about the case where you wish to use Ansible host targeting exclusions? Does that count as a 'host that you are not using anymore', from Ansible's perspective?

**Comment by boldandbusted** [comment]
> So Im guessing that if you have a machine listed in your inventory that you are not using anymore it can cause issues with magic variables.

So, does this appear to be an *Ansible* problem, or a problem steming from this role? It now feels like it is an Ansible problem. I wonder if there's a bug in the Ansible tracker....

I can replicate this problem when I have more hosts in the inventory for the Vagrant "ansible_local" provider than Vagrant created.

**Comment by santachago** [comment]
Hi i faced this issue today, seems that the default vars need to be updated too, the vault_raft_cluster_members variable is using hostvars[server] instead of hostvars[inventory_hostname]
