### ISSUE TITLE
Vault API reachable? problem

### ISSUE THREAD

**Issue by Daniel-Avo** [ansible-community/ansible-vault#214]
Hi,

When I was setting up a vault cluster at the last step problem occurred. When the playbook is trying to reach Vault API it is failing and errors appearing. How can I fix this?

![Capture](https://user-images.githubusercontent.com/63116280/109798527-26b09500-7c1b-11eb-9ca6-5c18b0c262b3.PNG)

**Comment by bbaassssiiee** [comment]
I notice a tunnel in your output, do you use ssh or nc or something to set that up? Is it actually up?

**Comment by Daniel-Avo** [comment]
VM that I am using is in the same server pool as nodes in Xenorchestra

**Comment by bbaassssiiee** [comment]
Is vault running?
Is there a port 8200 listening?
Can you connect to that port from localhost?
Can you connect remotely?

Run molecule converge to compare a vault in docker.

**Comment by Daniel-Avo** [comment]
![Capture](https://user-images.githubusercontent.com/63116280/109955633-ffbd9600-7ce2-11eb-8ba2-798fa0bdc058.PNG)

Vault at the first node is running on second and third not. I can not connect to that port via localhost either remotely.

**Comment by bbaassssiiee** [comment]
The issues here are for reporting bugs in the ansible-role, not for general support on Vault. Cannot reproduce it.
