### ISSUE TITLE
Swap 0.0.0.0 for 127.0.0.1 in VAULT_ADDR .bashrc export

### ISSUE THREAD

**Issue by user404d** [ansible-community/ansible-vault#217]
If the vault_address value is 0.0.0.0 then the exported VAULT_ADDR URL inherits this ip addr. The IP addr being 0.0.0.0 is problematic if TLS certificates are used to communicate using mTLS when neither the server or client certificate include 0.0.0.0 as an IP SAN entry. A common pattern is to include 127.0.0.1 or localhost as SAN entries in TLS certificates so using the same swapping behavior as seen in the [Vault Reachable?](https://github.com/ansible-community/ansible-vault/blob/master/tasks/main.yml#L276) check seems reasonable.

I have a draft of the change at #216. I might be making a reach about it being a common pattern to have 127.0.0.1 and localhost as SAN entries so please let me know if different behavior would be more appropriate. Thoughts?

**Comment by bbaassssiiee** [comment]
Thanks for spotting this, and creating an issue with your pull-request. I have no objections, a style-thingy might be that I would use a `set_fact:` instead of the action's `vars:`. _Being explicit..._

**Comment by user404d** [comment]
Thanks for merging :)
