### ISSUE TITLE
Use 'vault_config_path' as config argument

### ISSUE THREAD

**Issue by kevinschoonover** [ansible-community/ansible-vault#219]
Hello!

I ran into an issue yesterday where I was using cloud-init to add a configuration containing secrets at runtime; however, it was not getting picked up because the systemd vault config uses `-config={{vault_main_config}}` instead of `-config={{vault_config_path}}`.

I created a pull request #218 with I believe a backward-compatible way to do this but was wondering if this should be part of a larger depreciation effort as this seems to support a more general use case.

Thoughts?

**Comment by kevinschoonover** [comment]
Possibly closes #202

**Comment by bbaassssiiee** [comment]
As commented in the PR, please segregate the style-changes.
