### ISSUE TITLE
Unable to retrieve access keys when running Vault as a service

### ISSUE THREAD

**Issue by pchhum** [ansible-community/ansible-vault#22]
Hi,

I'm not sure if this is a newbie mistake on my end, but when I run Vault as a service using this role, I can't see the access tokens and root token to unseal vault. Is this an issue with the playbook or am I missing something very basic...

Thanks!!

**Comment by brianshumate** [comment]
Hey there @pchhum,

Thanks for reaching out; this is a first timer style question and that is totally fine!

You need `vault init` to generate the unseal keys and initial root token. This implies that you can connect to the running Vault instance from wherever you will call the `vault` CLI and to ensure success, you can set the environment variable `VAULT_ADDR` to the IP address (with protocol and port) that Vault is listening on.

When Vault is also not yet initialized, it is expected to see an error like this for `vault status`:

```
vault status
Error checking seal status: Error making API request.

URL: GET http://localhost:8200/v1/sys/seal-status
Code: 400. Errors:

* server is not yet initialized
```

So let's initialize Vault, and for example my Vault is configured with the IP address `10.1.42.42`:

```
export VAULT_ADDR=http://10.1.42.42:8200
vault init
Unseal Key 1: W5M0dRBpjnLZL79aR/zYr97YD8cz04fXJix6+ujF2hyt
Unseal Key 2: tH/sIt3o4yatEiTn2taVdRSUfOQkpigRKcrnHblBm8IR
Unseal Key 3: SYDhTVidkJmolDR8/ztGpm1/scwWkc54H7EbNT2taGnL
Unseal Key 4: 5sdEaUd5RfVupt2GBOo2ZbPnqKgQKm78KUG5pU0e90wT
Unseal Key 5: bbIfCjBVy2NDhyD6VoqXvw3Gf7J/cSjEAAr4IS75ds4F
Initial Root Token: f928dbb8-a5d6-176f-d866-f016d2844117

Vault initialized with 5 keys and a key threshold of 3. Please
securely distribute the above keys. When the vault is re-sealed,
restarted, or stopped, you must provide at least 3 of these keys
to unseal it again.

Vault does not store the master key. Without at least 3 keys,
your vault will remain permanently sealed.
```

Now that I have the unseal keys and initial root token, I can begin unsealing and using Vault.

I hope this helps you get going with Vault! You can also check out the [Vault Getting Started guide](https://www.vaultproject.io/intro/getting-started/install.html) and the rest of the great Vault documentation as well.

Regards,

Brian

**Comment by pchhum** [comment]
Wow Brian,

Thank you so much for taking the time to give an explanation. Very much appreciated! That was incredibly helpful. My only wish is that I could buy you a beer for your trouble.

Pan
