### ISSUE TITLE
Remove dependency on localhost

### ISSUE THREAD

**Issue by jtcarnes** [ansible-community/ansible-vault#223]
Right now, the role downloads content to the hosts local machine and copies the binaries from there to the targets. This is unneeded and doesn't scale well (as you have possibly many hosts trying to copy from your local machine instead of something that is built much more for many connections, such as the registries the binaries live in).

Instead of downloading files and then copying them to the targets, instead have the targets download the binaries themselves.

This is addressed in #222

**Comment by bbaassssiiee** [comment]
Please note that you can use the variable `vault_install_remotely` to drive this behaviour.

**Comment by jtcarnes** [comment]
You are absolutely right, i saw that after the pr. sorry for the noose!
