### ISSUE TITLE
Allow overriding main configuration template

### ISSUE THREAD

**Issue by arledesma** [ansible-community/ansible-vault#3]
#2 extended the backend template to be configurable, but the main template is still static.  It would be nice to be able to specify our own main template or at least exposing the following that are currently specified:

* ~~vault_cluster_name~~ (c01d293246ed94602cfbc79ad19e0e2bc026b32b #4)
* vault_tls_disable

And optionally include the following: 

* vault_cluster_address
* vault_tls_cert_file
* vault_tls_key_file
* vault_tls_min_version
* vault_tls_cipher_suites
* vault_tls_prefer_server_cipher_suites

**Comment by brianshumate** [comment]
Thanks for the feedback here!

I'll try to get something put together on this during the week.
