### ISSUE TITLE
Use without  Vagrant

### ISSUE THREAD

**Issue by bameur** [ansible-community/ansible-vault#32]
Can we use this role without the use of the Vagrant? for installation / configuration of a simple vault and in HA mode? 
Thank you in advance.

**Comment by brianshumate** [comment]
Hi!

Thanks for reaching out; yes, all of my Ansible roles work on any kind of infrastructure with a supported OS. You need only to define your hosts inventory and related variables and kick off a playbook that references the role.

There's an an example playbook, [site.yml](https://github.com/brianshumate/ansible-vault/blob/master/examples/site.yml) in the `examples` folder. There is also an example inventory file, [vagrant_hosts](https://github.com/brianshumate/ansible-vault/blob/master/examples/vagrant_hosts) and while these files are used for the Vagrantfile, they'll work with any host, if you just setup the hosts inventory per Ansible [Inventory documentation](https://docs.ansible.com/ansible/latest/intro_inventory.html).

For example, let's say that you have installed this role with:

```
$ ansible-galaxy install brianshumate.vault
```

and you have 3 Digital Ocean droplets that are reachable by the fully qualified domain names `vault0.example.com`, `vault1.example.com`, `vault2.example.com` by a user on the systems named `vadmin` which can use `sudo`.

All it takes to deploy this role to them is an inventory file like this example — let's say it's named `vault_digital_ocean`:

```
[vault_instances]
vault0.example.com ansible_ssh_user=vadmin ansible_ssh_private_key_file=/etc/pki/local/vault_example0_private_key

vault1.example.com ansible_ssh_user=vadmin ansible_ssh_private_key_file=/etc/pki/local/vault_example1_private_key

vault2.example.com ansible_ssh_user=vadmin ansible_ssh_private_key_file=/etc/pki/local/vault_example2_private_key
```

and an example `site.yml` like this:

```
---
# File: site.yml - Example Vault site playbook

- name: Install Vault
  hosts: vault_instances
  any_errors_fatal: true
  become: yes
  become_user: root
  roles:
    - { role: brianshumate.vault }

```

The the command to kick it all off would look like this:

```
$ ansible-playbook -i vault_digital_ocean site.yml
```

and that's it.

I would suggest that you check out the Ansible documentation on things like [installing roles](https://docs.ansible.com/ansible/latest/galaxy.html#installing-roles), [ansible-playbook](https://docs.ansible.com/ansible/latest/ansible-playbook.html), [inventory](https://docs.ansible.com/ansible/latest/intro_inventory.html) and perhaps [getting started](https://docs.ansible.com/ansible/latest/intro_getting_started.html) to learn more about executing roles against a given inventory.

I'll go ahead and mark this resolved now.
