### ISSUE TITLE
return code 429 is also valid in HA mode

### ISSUE THREAD

**Issue by dnABic** [ansible-community/ansible-vault#39]
In HA mode, only one vault node will become active node and therefore return status code 200 when queried for /sys/health. All other nodes will become standby and return 429 (unsealed and standby). Still, if return code 429 is returned, it means that node is unsealed and part of the "cluster". 

Would it make sense that task called "Vault API reachable? If not please unseal it" in tasks/main.yml accepts status_code 429 besides 200?

Rerefence: 
https://www.vaultproject.io/api/system/health.html
https://www.vaultproject.io/docs/concepts/ha.html

**Comment by brianshumate** [comment]
Hi, yes this would make sense. Thanks for the suggestion.
