### ISSUE TITLE
PIDFile in systemd script might not be necessary

### ISSUE THREAD

**Issue by derekmwright** [ansible-community/ansible-vault#41]
https://github.com/brianshumate/ansible-vault/blob/26979377067b25597afbd5dec90238b5569661fe/templates/vault_systemd.service.j2#L19

Looks like vault doesn't fork and `PIDFile=` is only there to reliably read the main PID of the process for tracking forks.

Per docs:

> PIDFile=
> Takes an absolute path referring to the PID file of the service. Usage of this option is recommended for services where Type= is set to forking. The service manager will read the PID of the main process of the service from this file after start-up of the service. *The service manager will not write to the file configured here*

https://www.freedesktop.org/software/systemd/man/systemd.service.html

I believe its safe to remove this option.

**Comment by brianshumate** [comment]
Hey there, thanks for the report and indeed that's some boilerplate. I'll remove it!

**Comment by brianshumate** [comment]
This is addressed in master, so I will close the issue now.
