### ISSUE TITLE
Add option to skip certificate validation in API reachability check

### ISSUE THREAD

**Issue by eripa** [ansible-community/ansible-vault#45]
Currently in the task **Vault API reachable? If not please unseal it** there's no support for skipping certificate validation. This is problematic since the `vault_address` defaults to an IP address. It can also be useful if you rely on self-signed certs. 

I can submit a PR for this.

**Comment by brianshumate** [comment]
Thanks! This is a good alternative to encoding IP SANs into your certificates for folks who don't want to do that.
