### ISSUE TITLE
Documentation Error:  vault_tls_server_crt_file

### ISSUE THREAD

**Issue by snesbittsea** [ansible-community/ansible-vault#53]
I believe there is a documentation error. If I'm not mistaken vault_tls_server_crt_file should be vault_tls_cert_file

**Comment by drewmullen** [comment]
yes, i agree. looks wrong to me too. in my inventory file, im actually parameterizing `vault_tls_cert_file`

**Comment by snesbittsea** [comment]
A grep of the github source asa of commit 6d6d74242dbb06844ff5d15d02451884b21a4767 does not contain a reference to vault_tls_server_crt_file except in the README
