### ISSUE TITLE
vault_tls_src_files isn't implemented

### ISSUE THREAD

**Issue by snesbittsea** [ansible-community/ansible-vault#54]
Based on the documentation I believe that the variable vault_tls_src_files should determine the path to the TLS files to be installed /etc/vault/tls. It's not working for me and performing a grep -r vault_tls_src_files in the tasks directory (on the most current install from ansible galaxy) brings up no hits.

Work around is to specify the full path for vault_tls_key_file and vault_tls_cert_file

Followup:
Interesting - the version I get with ansible-galaxy install is different than the github version. The github version does include vault_tls_src_files. The github version I'm comparing is showing 6d6d74242dbb06844ff5d15d02451884b21a4767 as latest commit.

**Comment by snesbittsea** [comment]
Interesting - the version I get with ansible-galaxy install is different than the github version. The github version does include vault_tls_src_files

**Comment by brianshumate** [comment]
Hey there,

I'm not sure what version you were using, but the Ansible Galaxy version is set to track a tagged release that must be imported into Galaxy, so it does not always necessarily match what's in other branches including the master branch at any given time.

I don't use the TLS functionality myself, but it seems to work as long as `vault_tls_disable` is set to zero.

**Comment by brianshumate** [comment]
Can you confirm that it either works as expected in version 2.0.3 as retrieved by `ansible-galaxy install brianshumate.vault` or not?

**Comment by brianshumate** [comment]
Howdy, any update here?

**Comment by seb-braun** [comment]
I confirm vault_tls_src_files works well for me with role v2.0.9 when:

- vault_tls_disable: false
- vault_tls_src_files: <FULL_PATH_OF_CERTS> <- contain ca.crt, vault.crt, vault.key

Hope that helps.

**Comment by brianshumate** [comment]
Thanks for the input @planetrobbie!

**Comment by brianshumate** [comment]
No news here, so closing this now.
