### ISSUE TITLE
vault_tls_ca_file variable not implemented

### ISSUE THREAD

**Issue by snesbittsea** [ansible-community/ansible-vault#55]
God, I hope I'm not just being clueless.

I had set the variable vault_tls_ca_file but with no effect. A grep of the source doesn't return any hits for this value.

If I get a chance I'll try to submit a patch, but it may be a couple of weeks

Follow up:
Same basic issue github version at commit 6d6d74242dbb06844ff5d15d02451884b21a4767 is not the same version as retrieved by the ansible-galaxy command. Github version does work. as expected and documented in this case.6d6d74242dbb06844ff5d15d02451884b21a4767 as latest commit.

**Comment by brianshumate** [comment]
Can you confirm that it either works as expected in version 2.0.3 as retrieved by `ansible-galaxy install brianshumate.vault` or not?

**Comment by brianshumate** [comment]
Howdy, any update here?

**Comment by snesbittsea** [comment]
I believe it works correctly, so let's close it.
