### ISSUE TITLE
Vault systemd service file on main branch fails on systemd 237

### ISSUE THREAD

**Issue by snesbittsea** [ansible-community/ansible-vault#56]
I am hoping that by this time you haven't stuck my picture on a dartboard.

I forked ansible-vault yesterday and have been using it instead of the galxy version. Unfortunately I found that the systemd vault service is invalid on my Ubuntu bionic system running systemd 237. There seem to be 3 problems:

- The Capabilities statement on line 26 is invalid. It appears to have been removed as per:
https://github.com/systemd/systemd/blob/master/NEWS. I *think* it needs to be incorporated into the CapabilityBoundingSet setting on line 27

- the mlock item on line 39 is causing Missing '=' messages. If I understand https://github.com/hashicorp/vault/issues/3605 then it can be removed since the presence of LimitMEMLOCK=infinity on line 40

- the StartLimitIntervalSec at 37 generates an unknown lvalue error. The https://github.com/systemd/systemd/blob/master/NEWS indicates that this item has been removed from the Service section to the Unit section.

- steve

**Comment by brianshumate** [comment]
Heyo, the systemd unit has been updated in [v2.0.5](https://github.com/brianshumate/ansible-vault/tree/v2.0.5)!
