### ISSUE TITLE
Systemd issues with 2.0.4

### ISSUE THREAD

**Issue by jeffWelling** [ansible-community/ansible-vault#62]
In the 2.0.4 tagged release, the systemd service file that is deployed appears to have an extraneous malformed line.

This line: https://github.com/brianshumate/ansible-vault/blob/v2.0.4/templates/vault_systemd.service.j2#L39

Is causing the following error, determined by trial-and-error removing different parts of the file:

    Sep 15 03:27:38 $HOSTNAME systemd[1]: [/usr/lib/systemd/system/vault.service:38] Missing '='.

I see that this is already resolved in the master branch, could you push a new tagged release at your earliest convenience?

Thanks kindly!

**Comment by brianshumate** [comment]
Heyo! Released [v2.0.5](https://github.com/brianshumate/ansible-vault/tree/v2.0.5) with the fix and Vault version 0.11.2.
