### ISSUE TITLE
Support for Vault Telemetry

### ISSUE THREAD

**Issue by jeffWelling** [ansible-community/ansible-vault#71]
Hello,
I'm interested in seeing this ansible-vault role support configuring telemetry information for vault. I've looked and there doesn't seem to be an option for this yet.

In the sister role for ansible-consul, this was implemented like so: https://github.com/brianshumate/ansible-consul#custom-configuration-section

I'm wondering if the same would work here, or if it instead just deserves it's own telemetry section.

Starting this Issue as a discussion point, I may end up implementing this myself.

**Comment by jeffWelling** [comment]
In the vault.service file, this could be accomplished by passing the config directory instead of a specific config file, this would cause vault to read all files in the directory, meaning administrators can drop in a telemetry.hcl file and it would be included.

**Comment by brianshumate** [comment]
Thanks for this, it's great addition indeed!
